# PagesCMS Configuration for Shroom-Mates
# This file configures the content management system for the shroom-mates.de website
# Documentation: https://pagescms.org/docs/configuration

# Media Configuration
# Configure where images and media files are stored
# IMPORTANT: Images in src/assets/ get optimized by Astro's Image component
# while files in public/ are served as-is without optimization
media:
  - name: images
    label: Bilder (Optimiert)
    input: src/assets/images
    output: src/assets/images
    categories: [image, video]
    description: Images here will be optimized by Astro
  - name: headings
    label: Überschriften (SVG)
    input: public/assets/headings
    output: /assets/headings
    categories: [image]
    description: SVG files served from public directory
  - name: public-assets
    label: Öffentliche Dateien
    input: public/assets
    output: /assets
    categories: [image, document]
    description: Static files served without optimization

# Content Configuration
# Define content types and their structure
content:
  # Landing Page - Unified content for index page
  # Contains hero section, teaser, values cards, and about us section
  - name: landing-page
    label: Startseite
    type: file
    path: src/content/landing-page/content.md
    format: yaml-frontmatter
    fields:
      - name: title
        label: Seitentitel
        type: string
        required: true
      
      # Hero Section
      - name: heroImage
        label: Hero-Bild
        type: image
        required: true
        description: Hero-Bild für die Startseite hochladen
        options:
          media: images
          extensions: [jpg, jpeg, png, webp]
          categories: [image]
      - name: heroImageAlt
        label: Hero-Bild Alt-Text
        type: string
        required: true
      - name: logoImage
        label: Logo-Bild
        type: image
        required: true
        description: Logo-Bild mit Pilzen hochladen
        options:
          media: images
          extensions: [png, svg, webp]
          categories: [image]
      - name: logoImageAlt
        label: Logo-Bild Alt-Text
        type: string
        required: true
      - name: heroTitle
        label: Hero-Überschrift
        type: string
        required: true
      - name: teaserText
        label: Teaser-Text
        type: text
        required: true
      
      # Values Section - List of value cards
      - name: values
        label: Werte-Karten
        type: object
        list:
          min: 1
          max: 3
          collapsible:
            collapsed: false
            summary: "{title} (#{index})"
        fields:
          - name: title
            label: Titel (für Barrierefreiheit)
            type: string
            required: true
            description: Text-Titel für Screen-Reader, wird nicht in der Überschrift angezeigt
          - name: headingSvg
            label: Überschrift SVG
            type: image
            required: true
            description: SVG-Datei für die Überschrift hochladen
            options:
              media: headings
              extensions: [svg]
              categories: [image]
          - name: description
            label: Beschreibung
            type: text
            required: true
      
      # About Us Section
      - name: aboutUsHeadingSvg
        label: Über Uns Überschrift SVG
        type: image
        required: true
        description: SVG-Datei für die "Über Uns" Überschrift hochladen
        options:
          media: headings
          extensions: [svg]
          categories: [image]
      - name: aboutUsTitle
        label: Über Uns Titel (für Barrierefreiheit)
        type: string
        required: true
        description: Text-Titel für Screen-Reader
      
      # About Us Content (body)
      - name: body
        label: Über Uns Inhalt
        type: rich-text
        required: true
        options:
          media: false
      
      # Mushroom Showcase Section
      - name: mushroomShowcaseHeadingSvg
        label: Pilz-Showcase Überschrift SVG
        type: image
        required: true
        description: SVG-Datei für die Pilz-Showcase Überschrift hochladen
        options:
          media: headings
          extensions: [svg]
          categories: [image]
      - name: mushroomShowcaseTitle
        label: Pilz-Showcase Titel (für Barrierefreiheit)
        type: string
        required: true
        description: Text-Titel für Screen-Reader
      - name: mushroomShowcaseImage
        label: Pilz-Showcase Bild
        type: image
        required: true
        description: Hochauflösendes Pilzbild hochladen
        options:
          media: images
          extensions: [jpg, jpeg, png, webp]
          categories: [image]
      - name: mushroomShowcaseImageAlt
        label: Pilz-Showcase Bild Alt-Text
        type: string
        required: true
      - name: mushroomShowcaseText
        label: Pilz-Showcase Text
        type: text
        required: true
        description: Kurzer Text über die Pilze
      
      # Mushrooms Array - for "Unsere Pilze" page
      - name: mushrooms
        label: Pilze-Übersicht
        type: object
        list:
          min: 0
          collapsible:
            collapsed: false
            summary: "{title} (#{index})"
        fields:
          - name: title
            label: Pilzsorte
            type: string
            required: true
          - name: image
            label: Pilz-Bild
            type: image
            required: true
            description: Hochauflösendes Bild der Pilzsorte hochladen
            options:
              media: images
              extensions: [jpg, jpeg, png, webp]
              categories: [image]
          - name: imageAlt
            label: Bild Alt-Text
            type: string
            required: true
          - name: description
            label: Beschreibung
            type: text
            required: true
            description: Kurze Beschreibung der Pilzsorte

# Components
# Reusable field groups (currently not used but available for future use)
components:
  # SEO Meta Information
  seo:
    label: SEO-Einstellungen
    type: object
    fields:
      - name: metaTitle
        label: Meta-Titel
        type: string
        required: false
      - name: metaDescription
        label: Meta-Beschreibung
        type: string
        required: false
      - name: ogImage
        label: Social Media Bild
        type: image
        required: false
