# PagesCMS Configuration for Shroom-Mates
# This file configures the content management system for the shroom-mates.de website
# Documentation: https://pagescms.org/docs/configuration

# Media Configuration
# Configure where images and media files are stored
media:
  - name: images
    label: Bilder
    input: src/assets/images
    output: /assets/images
    categories: [image, video]
  - name: headings
    label: Überschriften (SVG)
    input: public/assets/headings
    output: /assets/headings
    categories: [image]
  - name: public-assets
    label: Öffentliche Dateien
    input: public/assets
    output: /assets
    categories: [image, document]

# Content Configuration
# Define content types and their structure
content:
  # Landing Page - Unified content for index page
  # Contains hero section, teaser, values cards, and about us section
  - name: landing-page
    label: Startseite
    type: file
    path: src/content/landing-page/content.md
    format: yaml-frontmatter
    fields:
      - name: title
        label: Seitentitel
        type: string
        required: true
      
      # Hero Section
      - name: heroImage
        label: Hero-Bild
        type: string
        required: true
        hint: Dateiname des Hero-Bildes (z.B. hero_rose_tasse.jpg)
      - name: heroImageAlt
        label: Hero-Bild Alt-Text
        type: string
        required: true
      - name: logoImage
        label: Logo-Bild
        type: string
        required: true
        hint: Dateiname des Logo-Bildes (z.B. logo_with_shrooms.png)
      - name: logoImageAlt
        label: Logo-Bild Alt-Text
        type: string
        required: true
      - name: heroTitle
        label: Hero-Überschrift
        type: string
        required: true
      - name: teaserText
        label: Teaser-Text
        type: text
        required: true
      
      # Values Section
      - name: values
        label: Werte-Karten
        type: list
        required: true
        fields:
          - name: title
            label: Titel (für Barrierefreiheit)
            type: string
            required: true
            hint: Text-Titel für Screen-Reader, wird nicht angezeigt
          - name: order
            label: Reihenfolge
            type: number
            required: true
          - name: headingSvg
            label: Überschrift SVG
            type: string
            required: true
            hint: Voller Pfad zur SVG-Datei (z.B. /assets/headings/nachhaltig.svg)
          - name: description
            label: Beschreibung
            type: text
            required: true
      
      # About Us Section
      - name: aboutUsHeadingSvg
        label: Über Uns Überschrift SVG
        type: string
        required: true
        hint: Voller Pfad zur SVG-Datei (z.B. /assets/headings/ueber_uns.svg)
      - name: aboutUsTitle
        label: Über Uns Titel (für Barrierefreiheit)
        type: string
        required: true
        hint: Text-Titel für Screen-Reader
      
      # About Us Content (body)
      - name: body
        label: Über Uns Inhalt
        type: rich-text
        required: true

  # Values Collection (kept for backward compatibility)
  # Three value cards on the landing page
  - name: values
    label: Werte-Karten (Alt)
    type: collection
    path: src/content/values
    format: yaml-frontmatter
    view:
      fields: [title, order]
      primary: title
      sort: [order]
      default:
        sort: order
        order: asc
    fields:
      - name: title
        label: Titel
        type: string
        required: true
      - name: order
        label: Reihenfolge
        type: number
        required: true
      - name: body
        label: Beschreibung
        type: text
        required: true

  # About Us Section (kept for backward compatibility)
  # Content for the about us section with markdown paragraphs
  - name: about-us
    label: Über Uns (Alt)
    type: file
    path: src/content/about-us/content.md
    format: yaml-frontmatter
    fields:
      - name: title
        label: Titel
        type: string
        required: true
      - name: body
        label: Inhalt
        type: rich-text
        required: true

# Components
# Reusable field groups
components:
  # SEO Meta Information
  seo:
    label: SEO-Einstellungen
    fields:
      - name: metaTitle
        label: Meta-Titel
        type: string
        required: false
      - name: metaDescription
        label: Meta-Beschreibung
        type: string
        required: false
      - name: ogImage
        label: Social Media Bild
        type: image
        required: false
