# PagesCMS Configuration for Shroom-Mates
# This file configures the content management system for the shroom-mates.de website
# Documentation: https://pagescms.org/docs/configuration

# Media Configuration
# Configure where images and media files are stored
# IMPORTANT: Images in src/assets/ get optimized by Astro's Image component
# while files in public/ are served as-is without optimization
# The 'output' path is what gets written in the markdown frontmatter
# It must be relative to the content file location (e.g., src/content/mushrooms/)
media:
  - name: images
    label: Bilder (Optimiert)
    input: src/assets/images
    output: ../../assets/images
    categories: [image, video]
    description: Images here will be optimized by Astro
  - name: headings
    label: Überschriften (SVG)
    input: public/assets/headings
    output: /assets/headings
    categories: [image]
    description: SVG files served from public directory
  - name: public-assets
    label: Öffentliche Dateien
    input: public/assets
    output: /assets
    categories: [image, document]
    description: Static files served without optimization

# Content Configuration
# Define content types and their structure
content:
  # Landing Page - Unified content for index page
  # Contains hero section, teaser, values cards, and about us section
  - name: landing-page
    label: Startseite
    type: file
    path: src/content/landing-page/content.md
    format: yaml-frontmatter
    fields:
      - name: title
        label: Seitentitel
        type: string
        required: true
      
      # Hero Section
      - name: heroImage
        label: Hero-Bild
        type: image
        required: true
        description: Hero-Bild für die Startseite hochladen
        options:
          media: images
          extensions: [jpg, jpeg, png, webp]
          categories: [image]
      - name: heroImageAlt
        label: Hero-Bild Alt-Text
        type: string
        required: true
      - name: logoImage
        label: Logo-Bild
        type: image
        required: true
        description: Logo-Bild mit Pilzen hochladen
        options:
          media: images
          extensions: [png, svg, webp]
          categories: [image]
      - name: logoImageAlt
        label: Logo-Bild Alt-Text
        type: string
        required: true
      - name: heroTitle
        label: Hero-Überschrift
        type: string
        required: true
      - name: teaserText
        label: Teaser-Text
        type: text
        required: true
      
      # Values Section - List of value cards
      - name: values
        label: Werte-Karten
        type: object
        list:
          min: 1
          max: 3
          collapsible:
            collapsed: false
            summary: "{title} (#{index})"
        fields:
          - name: title
            label: Titel (für Barrierefreiheit)
            type: string
            required: true
            description: Text-Titel für Screen-Reader, wird nicht in der Überschrift angezeigt
          - name: headingSvg
            label: Überschrift SVG
            type: image
            required: true
            description: SVG-Datei für die Überschrift hochladen
            options:
              media: headings
              extensions: [svg]
              categories: [image]
          - name: description
            label: Beschreibung
            type: text
            required: true
      
      # Mushroom Showcase Section
      - name: mushroomShowcaseHeadingSvg
        label: Pilz-Showcase Überschrift SVG
        type: image
        required: true
        description: SVG-Datei für die Pilz-Showcase Überschrift hochladen
        options:
          media: headings
          extensions: [svg]
          categories: [image]
      - name: mushroomShowcaseTitle
        label: Pilz-Showcase Titel (für Barrierefreiheit)
        type: string
        required: true
        description: Text-Titel für Screen-Reader
      - name: mushroomShowcaseImage
        label: Pilz-Showcase Bild
        type: image
        required: true
        description: Hochauflösendes Pilzbild hochladen
        options:
          media: images
          extensions: [jpg, jpeg, png, webp]
          categories: [image]
      - name: mushroomShowcaseImageAlt
        label: Pilz-Showcase Bild Alt-Text
        type: string
        required: true
      - name: mushroomShowcaseGrowingMethodsText
        label: Pilz-Showcase Text
        type: text
        required: false
        description: Kurzer Text über Anbaumethoden und Qualität

  # Mushrooms Collection - Individual mushroom types for "Unsere Pilze" page
  - name: mushrooms
    label: Pilzsorten
    type: collection
    path: src/content/mushrooms
    format: yaml-frontmatter
    extension: md
    fields:
      - name: title
        label: Pilzsorte
        type: string
        required: true
        description: Name der Pilzsorte (z.B. "Austernpilze")
      - name: image
        label: Pilz-Bild
        type: image
        required: true
        description: Hochauflösendes Bild der Pilzsorte hochladen
        options:
          media: images
          extensions: [jpg, jpeg, png, webp]
          categories: [image]
      - name: imageAlt
        label: Bild Alt-Text
        type: string
        required: true
        description: Beschreibender Alt-Text für das Bild (Barrierefreiheit)
      - name: color
        label: Hintergrundfarbe
        type: string
        required: false
        description: Hex-Farbe für den Textbox-Hintergrund (z.B. "#f6efe6")
        default: "#ffffff"
      - name: order
        label: Sortierung
        type: number
        required: true
        description: Reihenfolge auf der Seite (1, 2, 3, ...)
        default: 1
      - name: body
        label: Beschreibung
        type: rich-text
        required: true
        description: Ausführliche Beschreibung der Pilzsorte
        options:
          media: false

  # About Us Page - Content for the about us page
  - name: about-us-page
    label: Über Uns Seite
    type: file
    path: src/content/about-us-page/content.md
    format: yaml-frontmatter
    fields:
      - name: title
        label: Seitentitel
        type: string
        required: true
        description: SEO-optimierter Titel für die Seite
      - name: description
        label: Meta-Beschreibung
        type: text
        required: true
        description: SEO-Beschreibung für Suchmaschinen
      - name: heroTitle
        label: Haupt-Überschrift
        type: string
        required: true
        description: Große Überschrift auf der Seite
      - name: heroSubtitle
        label: Untertitel
        type: string
        required: false
        description: Optional: Untertitel unter der Hauptüberschrift
      - name: body
        label: Inhalt
        type: rich-text
        required: false
        description: Ausführlicher Text über das Team, Arbeitsweise, Werte etc.
        options:
          media: false
      - name: images
        label: Bilder-Galerie
        type: image
        required: true
        description: Bilder aus dem Labor, Team-Fotos, oder Pilzfotos hochladen
        options:
          media: images
          extensions: [jpg, jpeg, png, webp]
          categories: [image]
          multiple:
            max: 10

  # Growkits Page - Generic instructions for all growkits
  - name: growkits-page
    label: Growkits Seite
    type: file
    path: src/content/growkits-page/content.md
    format: yaml-frontmatter
    fields:
      - name: title
        label: Seitentitel
        type: string
        required: true
        description: SEO-optimierter Titel für die Seite
      - name: description
        label: Meta-Beschreibung
        type: text
        required: true
        description: SEO-Beschreibung für Suchmaschinen
      - name: heroTitle
        label: Haupt-Überschrift
        type: string
        required: true
        description: Große Überschrift auf der Seite
      - name: heroSubtitle
        label: Untertitel
        type: string
        required: true
        description: Untertitel unter der Hauptüberschrift
      - name: heroImage
        label: Hero-Bild
        type: image
        required: true
        description: Bild für die Seite
        options:
          media: images
          extensions: [jpg, jpeg, png, webp]
          categories: [image]
      - name: heroImageAlt
        label: Hero-Bild Alt-Text
        type: string
        required: true
        description: Beschreibender Alt-Text für das Hero-Bild
      - name: ctaTitle
        label: CTA Überschrift
        type: string
        required: true
        description: Überschrift für den Call-to-Action Bereich
      - name: ctaText
        label: CTA Text
        type: text
        required: true
        description: Text für den Call-to-Action Bereich
      - name: ctaButtonText
        label: CTA Button Text
        type: string
        required: true
        description: Text für den Button (z.B. "Kontakt aufnehmen")
      - name: ctaButtonLink
        label: CTA Button Link
        type: string
        required: true
        description: Link für den Button (z.B. "/kontakt")
      - name: body
        label: Anleitung
        type: rich-text
        required: true
        description: Allgemeine Anleitung für alle Growkits (Markdown)
        options:
          media: false
  - name: growkits
    label: Growkit Sorten
    type: collection
    path: src/content/growkits
    format: yaml-frontmatter
    extension: md
    fields:
      - name: title
        label: Growkit Name
        type: string
        required: true
        description: Name des Growkits (z.B. "Lion's Mane Growkit")
      - name: image
        label: Growkit-Bild
        type: image
        required: true
        description: Bild des Pilzes oder Growkits hochladen
        options:
          media: images
          extensions: [jpg, jpeg, png, webp]
          categories: [image]
      - name: imageAlt
        label: Bild Alt-Text
        type: string
        required: true
        description: Beschreibender Alt-Text für das Bild (Barrierefreiheit)
      - name: color
        label: Hintergrundfarbe
        type: string
        required: false
        description: Hex-Farbe für den Abschnitt-Hintergrund (z.B. "#ffe4ec")
        default: "#ffffff"
      - name: order
        label: Sortierung
        type: number
        required: true
        description: Reihenfolge auf der Seite (1, 2, 3, ...)
        default: 1
      - name: body
        label: Beschreibung
        type: rich-text
        required: true
        description: Ausführliche Beschreibung des Growkits
        options:
          media: false

  # FAQ Page - FAQ items as an array in a single file
  - name: faq-page
    label: FAQ Seite
    type: file
    path: src/content/faq-page/content.md
    format: yaml-frontmatter
    fields:
      - name: title
        label: Seitentitel
        type: string
        required: true
        description: SEO-Titel für die FAQ-Seite
      - name: description
        label: Meta-Beschreibung
        type: text
        required: true
        description: SEO-Beschreibung für Suchmaschinen
      - name: faqs
        label: FAQ Einträge
        type: object
        list:
          min: 1
          collapsible:
            collapsed: true
            summary: "{question}"
        fields:
          - name: question
            label: Frage
            type: string
            required: true
          - name: answer
            label: Antwort
            type: text
            required: true
          - name: link
            label: Link (optional)
            type: string
            required: false
            description: Link zu einer Seite mit mehr Informationen (z.B. "/growkits")

# Components
# Reusable field groups (currently not used but available for future use)
components:
  # SEO Meta Information
  seo:
    label: SEO-Einstellungen
    type: object
    fields:
      - name: metaTitle
        label: Meta-Titel
        type: string
        required: false
      - name: metaDescription
        label: Meta-Beschreibung
        type: string
        required: false
      - name: ogImage
        label: Social Media Bild
        type: image
        required: false
